stages:
  - build

.parallel-hidden-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
  parallel:
    matrix:
      - ARCH: [x64, aarch64]

build-job:
  image: bilelmoussaoui/flatpak-github-actions:gnome-46
  extends: .parallel-hidden-job
  stage: build
  script:
    - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - gpg --list-keys --with-keygrip
    - echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
    - gpg-connect-agent reloadagent /bye
    - cat $GPG_PASSPHRASE | /usr/libexec/gpg-preset-passphrase --preset $GPG_KEY_GREP
    - gpg --import --batch ${GPG_PRIVATE_KEY}

    - flatpak-builder build --user --install-deps-from=flathub --gpg-sign=${GPG_KEY_ID} --disable-rofiles-fuse --disable-updates --force-clean --repo=repo ${BRANCH:+--default-branch=$BRANCH} $CI_PROJECT_DIR/source/data/manifest.json
    - flatpak build-bundle --gpg-sign=${GPG_KEY_ID} repo ${APP_ID}.${ARCH}.flatpak --runtime-repo=flathub ${APP_ID} ${BRANCH}
    - flatpak build-update-repo --gpg-sign=${GPG_KEY_ID} --generate-static-deltas --prune repo/
  artifacts:
    paths:
      - repo
